apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "grafana.name" . }}-storage
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}