apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.name" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
  {{- include "grafana.labels" . | nindent 4 }}
spec:
  selector:
  {{- include "grafana.selectorLabels" . | nindent 6 }}
  ports:
  - port: 3000
    targetPort: 3000
