apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.name" . }}-alertmanager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
  labels:
  {{ include "prometheus.labels" . | nindent 4}}
spec:
  selector:
  {{ include "prometheus.selectorLabels" . | nindent 4}}
  ports:
    - port: 9093
      targetPort: 9093
