apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "prometheus.name" . }}
  labels:
  {{ include "prometheus.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus.name" . }}
