prometheus:
  image:
    repository: docker.repo.schwarz/prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent
  
  # pvc size
  storage: 1Gi

  requests:
    memory: "250Mi"
    cpu: "100m"
  limits:
    memory: "500Mi"
    cpu: "200m"

  #only for standalone deployment
  federationUser: # insert_federation_user
  federationPassword: # insert_federation_password

alertmanager:
  image:
    repository: docker.repo.schwarz/prom/alertmanager
    tag: latest
    pullPolicy: IfNotPresent

  # pvc size
  storage: 1Gi

  #only for standalone deployment
  mailto: #insert_mail

#only for standalone deployment
global:
  namespace:
  app: monitoring




