federationUser: #required for standalone deployment
federationPassword: #required for standalone deployment

prometheus:
  image:
    repository: docker.repo.schwarz/prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent
  # pvc size
  storage: 1Gi
  # quota
  requests:
    memory: "250Mi"
    cpu: "100m"
  limits:
    memory: "500Mi"
    cpu: "200m"

alertmanager:
  image:
    repository: docker.repo.schwarz/prom/alertmanager
    tag: latest
    pullPolicy: IfNotPresent
  # pvc size
  storage: 1Gi

  mailto: #required for standalone deployment

global:
  namespace: #required for standalone deployment
  app: monitoring




