kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "prometheus.name" . }}-alertmanager
  labels:
  {{ include "prometheus.labels" . | nindent 4 }}
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: "systemmail.mail.schwarz:25"
      smtp_from: altermanager.{{ required "namespace is required!" .Values.global.namespace }}@mail.schwarz
      smtp_require_tls: false

    templates:
      - "/etc/alertmanager/template/*.tmpl"

    route:
      group_by: ["alertname", "cluster", "service"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: default

    receivers:
      - name: default
        email_configs:
          - to: {{ required "mailto for alertmanager is required!" .Values.alertmanager.mailto | quote }}
