apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus.name" . }}-alertmanager-storage
  labels:
  {{ include "prometheus.labels" . | nindent 4}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.alertmanager.storage  }}
