apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.name" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
  {{ include "prometheus.labels" . | nindent 4}}
spec:
  selector:
  {{ include "prometheus.selectorLabels" . | nindent 4}}
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090