image:
  repository: docker.repo.schwarz/grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

pvc:
  storage: 500Mi

# resource limits
resources:
  memory: 500Mi
  cpu:  1


global:
  namespace:  #required for standalone deployment
  app: monitoring